import Settings from "./Settings";

interface Language {
    it?: string,
    fallback?: string
}

const translation = new Map<string, Language>([
    ["Upload files", {it: "Carica file"}],
    ["Pick multiple files", {it: "Scegli dei file"}],
    ["Pick a folder", {it: "Scegli una cartella"}],
    ["Sort files", {it: "Ordina file"}],
    ["By last modified date", {it: "Per l'ultima data di modifica"}],
    ["By size", {it: "Per dimensione"}],
    ["By name", {it: "Per nome"}],
    ["Reverse order", {it: "Inverti ordine"}],
    ["Select files", {it: "Seleziona file"}],
    ["Settings", {it: "Impostazioni"}],
    ["Loading files, please wait", {it: "Carico file, attendere"}],
    ["Go back", {it: "Torna indietro"}],
    ["The application can't write in this folder", {it: "L'applicazione non può scrivere in questa cartella"}],
    [`You won't be able to upload files to this folder until you don't select it from the "Access to external drives" section of the mobile application`, {it: `Non potrai caricare file in questa cartella fino a che non la selezionerai dalla sezione "Accedi ai dischi esterni" dell'applicazione mobile`}],
    ["Sorted by this column", {it: "Ordinati per questa colonna"}],
    ["File name", {it: "Nome del file"}],
    ["Last modified date", {it: "Data di ultima modifica"}],
    ["File size", {it: "Dimensioni del file"}],
    ["Sorted by this column", {it: "Ordinati da questa colonna"}],
    ["File mimetype", {it: "Mimetype del file"}],
    ["Not calculated", {it: "Non calcolato"}],
    ["Folder", {it: "Cartella"}],
    ["File icon", {it: "Icona del file"}],
    ["Last modified", {it: "Ultima modifica"}],
    ["Size", {it: "Dimensioni"}],
    ["Do you want to delete all the selected files? This action can't be undone.", {it: "Vuoi eliminare tutti i file selezionati? Quest'azione non può essere annullata."}],
    ["Background album art", {it: "Copertina dell'album di sfondo"}],
    ["Change buttons height", {it: "Cambia l'altezza dei pulsanti"}],
    ["Zoom in", {it: "Aumenta zoom"}],
    ["Zoom out", {it: "Diminuisci zoom"}],
    ["Fetching audio files", {it: "Ottengo file audio"}],
    ["Your", {it: "I tuoi"}],
    ["Your F", {it: "Le tue", fallback: "Your"}],
    ["albums", {it: "album"}],
    ["artists", {it: "artisti"}],
    ["album artists", {it: "artisti dell'album"}],
    ["tracks", {it: "tracce"}],
    ["Thumbnail of", {it: "Copertina di"}],
    ["Unknown", {it: "Sconosciuto"}],
    ["Next album art", {it: "Prossima copertina dell'album"}],
    ["Close dialog", {it: "Chiudi pop-up"}],
    ["Unknown album", {it: "Album sconosciuto"}],
    ["Unknown artist", {it: "Artista sconosciuto"}],
    ["Enable/disable shuffle", {it: "Abilita/disabilita riproduzione casuale"}],
    ["Previous track", {it: "Traccia precedente"}],
    ["Play/pause", {it: "Riproduci/metti in pausa"}],
    ["Next track", {it: "Prossima traccia"}],
    ["Toggle between repeat options", {it: "Cambia le opzioni di ripetizione"}],
    ["Change playback rate", {it: "Cambia la velocità di riproduzione"}],
    ["Toggle picture-in-picture for this video", {it: "Abilita/disabilita il picture-in-picture per questo video"}],
    ["Toggle fullscreen mode", {it: "Abilita/disabilita modalità a schermo intero"}],
    ["Change volume", {it: "Cambia volume"}],
    ["Taken on", {it: "Scattata il"}],
    ["Download", {it: "Scarica"}],
    ["Close preview", {it: "Chiudi anteprima"}],
    ["Metadata", {it: "Metadati"}],
    ["Image size", {it: "Dimensione dell'immagine"}],
    ["Video size", {it: "Dimensione del video"}],
    ["Metadata list", {it: "Lista dei metadati"}],
    ["Change image height", {it: "Cambia l'altezza delle immagini"}],
    ["Select mode enabled", {it: "Modalità di selezione attivata"}],
    ["Mass select mode enabled", {it: "Modalità di selezione di massa attivata"}],
    ["click two items, and all the elements between them will be selected", {it: "clicca due elementi, e gli elementi tra di loro verranno selezionati"}],
    ["click on an item to select it", {it: "clicca su un elemento per selezionarlo"}],
    ["Toggle mass selection mode", {it: "Abilita/disabilita modalità di selezione di massa"}],
    ["Download files", {it: "Scarica file"}],
    ["Delete files", {it: "Elimina file"}],
    ["Disable select mode", {it: "Disabilita modalità di selezione"}],
    ["Here you can find all the open source software used by WebShare", {it: "Qui puoi trovare tutto il software open source utilizzato da WebShare"}],
    ["Already added entries (click to remove)", {it: "Elementi già aggiunti (clicca per rimuovere)"}],
    ["Settings", {it: "Impostazioni"}],
    ["Photo viewer:", {it: "Visualizzatore foto"}],
    ["Default path for image upload", {it: "Percorso predefinito per il caricamento delle immagini"}],
    ["Default path for video upload", {it: "Percorso predefinito per il caircamento dei video"}],
    ["Ask every time if the files should be uploaded in a subfolder", {it: "Chiedi ogni volta se i file dovrebbero essere caricati in una sottocartella"}],
    ["Default photo height (in pixels)", {it: "Altezza della foto predefinita (in pixel)"}],
    ["When zooming, increase/decrease the picture of (in pixels)", {it: "Quando si usa lo zoom, ingrandisci/diminuisci le foto di (in pixel)"}],
    ["Show the video duration in the bottom-left corner of the photo viewer", {it: "Mostra la durata del video nell'angolo in basso a sinistra del visualizzatore delle foto"}],
    ["Album viewer:", {it: "Visualizzatore album:"}],
    ["If a folder has the same name, but it's stored in a different path (ex: Downloads/A and Pictures/A), put them in two different albums", {it: "Se una cartella ha lo stesso nome, ma è salvata in un percorso differente (es: Downloads/A e Pictures/A), crea due album differenti"}],
    ["File viewer:", {it: "Visualizzatore dei file:"}],
    ["File information:", {it: "Informazioni dei file:"}],
    ["Show the last modified date below each file name", {it: "Mostra la data di ultima modifica sotto ogni nome del file"}],
    ["Show the file mimetype below each file name", {it: "Mostra il mimetype del file sotto ogni nome del file"}],
    ["Show the file size below each file name", {it: "Mostra le dimensioni del file sotto ogni nome del file"}],
    ["Sorting options", {it: "Impostazioni nell'ordine"}],
    ["Default sorting option", {it: "Ordine predefinito"}],
    ["by file name", {it: "per nome del file"}],
    ["by last modified date", {it: "per data di ultima modifica"}],
    ["by file size", {it: "per dimensioni del file"}],
    ["Automatically reverse the list", {it: "Inverti automaticamente la lista"}],
    ["Grid options", {it: "Impostazioni della griglia"}],
    ["Show files in a table instead of a grid", {it: "Mostra i file in una tabella rispetto ad una griglia"}],
    ["Show a preview for image and video files", {it: "Mostra l'anteprima per le immagini ed i video"}],
    ["Show a preview for audio files", {it: "Mostra l'anteprima per i file audio"}],
    ["Show a preview for PDF files", {it: "Mostra l'anteprima per i file PDF"}],
    ["Songs viewer:", {it: "Visualizzatore delle canzoni:"}],
    ["General settings", {it: "Impostazioni generali"}],
    ["Default path for audio upload", {it: "Percorso predefinito per il caricamento degli audio"}],
    ["Enable compact mode", {it: "Abilita la modalità compatta"}],
    ["Show songs in a table instead of a grid", {it: "Mostra le canzoni in una tabella invece che in una griglia"}],
    ["Fallback album art colors", {it: "Colori delle copertine degli album"}],
    ["Artist division (experimental)", {it: "Divisione degli artisti (sperimentale)"}],
    ["Sometimes, you might have some artists split by some characters (for example, a comma). Here you can put these symbols so that you'll be able to treat `Artist A, Artist B` as two separate artists", {it: "A volte, potresti avere degli artisti divisi da alcuni caratteri (per esempio, una virgola). Qui puoi inserire questi simboli, in modo da trattare `Artista A, Artista B` come due artisti separati"}],
    ["For artists", {it: "Per gli artisti"}],
    ["For album artists", {it: "Per gli artisti dell'album"}],
    ["Application theme:", {it: "Tema dell'applicazione:"}],
    ["Get colors from the smartphone's theme", {it: "Ottieni il colore dal tema dello smartphone"}],
    ["Custom colors", {it: "Colore personalizzato"}],
    ["Application behavior:", {it: "Comportamento dell'applicazione:"}],
    ["Default application section", {it: "Sezione predefinta dell'applicazione"}],
    ["photos and videos", {it: "foto e video"}],
    ["albums", {it: "album"}],
    ["songs", {it: "canzoni"}],
    ["files", {it: "file"}],
    ["Uploading files", {it: "Caricamento dei file"}],
    ["Failed upload of", {it: "Caricamento fallito di"}],
    ["Welcome to WebShare. To log in and see all the files on your device, please write the code you can obtain from the \"Get authentication code\" button from your phone", {it: "Benvenuto su WebShare. Per accedere e vedere tutti i file salvati sul tuo dispositivo, per favore scrivi il codice che puoi ottenere dal pulsante \"Ottieni codice di autenticazione\" presente sul tuo telefono"}],
    ["Login", {it: "Accedi"}],
    ["Change album art size", {it: "Cambia dimensioni della copertina dell'album"}],
    ["Change table size", {it: "Cambia dimensioni della tabella"}],
    ["Image", {it: "Immagine"}],
    ["Album", {it: "Album"}],
    ["Artists", {it: "Artisti"}],
    ["Album artists", {it: "Artisti dell'album"}],
    ["Composerr", {it: "Compositore"}],
    ["Track", {it: "Traccia"}],
    ["Genre", {it: "Genere"}],
    ["Disc", {it: "Disco"}],
    ["Year", {it: "Anno"}],
    ["Duration", {it: "Durata"}],
    ["Bitrate", {it: "Bitrate"}],
    ["Track number", {it: "Numero della traccia"}],
    ["Disc number", {it: "Numero del disco"}],
    ["Increase table width", {it: "Aumenta larghezza della tabella"}],
    ["Decrease table width", {it: "Diminuisci larghezza della tabella"}],
    ["Location map style", {it: "Stile della mappa delle posizioni"}],
    ["Default", {it: "Predefinito"}],
    ["Light", {it: "Chiaro"}],
    ["Dark", {it: "Scuro"}],
    ["Satellite", {it: "Satellite"}],
    ["Delete image", {it: "Elimina immagine"}],
    ["Do you want to delete the selected image? This action can't be undone.", {it: "Vuoi eliminare l'immagine selezionata? Quest'azione non può essere annullata."}],
    ["Metadata to show in the table", {it: "Metadati da mostrare nella tabella"}],
    ["Change the volume level", {it: "Cambia il livello del volume"}],
    ["Change volume", {it: "Cambia volume"}],
    ["Dismiss", {it: "Rimuovi"}],
    ["Try again", {it: "Prova di nuovo"}],
    ["Download multiple items:", {it: "Scarica più elementi:"}],
    ["Download multiple files directly on the device if possible. If disabled or not supported by the browser, a zip file will be downloaded.", {it: "Scarica più file direttamente nel dispositivo se possibile. Se disabilitato o non supportato dal browser, un file zip verrà scaricato."}],
    ["Replace the files saved on this device", {it: "Sostituisci i file salvati su questo dispositivo"}],
    ["Maximum concurrent downloads", {it: "Massimo numero di download simultanei"}],
    ["Load more items", {it: "Carica più elementi"}],
    ["How do you want to name the new folder?", {it: "Come vuoi chiamare la nuova cartella?"}],
    ["Create folder", {it: "Crea cartella"}],
    ["If a file already exists, replace it", {it: "Sostituisci un file se esiste di già"}],
    ["File upload:", {it: "Caricamento dei file:"}],
    ["Is favorite", {it: "È preferito"}],
    ["Add image to favorites", {it: "Aggiungi immagine ai preferiti"}],
    ["Remove image from favorites", {it: "Rimuovi immagine dai preferiti"}],
    ["No album", {it: "Nessun album"}],
    ["Favorites", {it: "Preferiti"}],
    ["Add/remove from favorites", {it: "Aggiungi/rimuovi dai preferiti"}],
    ["Go to the next image when an image has been deleted in the fullscreen viewer mode. If disabled, the website will close the fullscreen photo viewer", {it: "Vai all'immagine successiva quando un'immagine viene eliminata nella modalità di visualizzazione a schermo intero. Se disabilitato, il sito chiuderà il visualizzatore delle foto a schermo intero"}]
]);

/**
 * Translate a string
 * @param str the string to translate
 * @returns the translated string, or the same string if no result has been found
 */
export default function lang(str: string) {
    const translated = translation.get(str);
    if (translated?.[Settings.language as "it"]) return translated?.[Settings.language as "it"] as string;
    return translated?.fallback ?? str;
}